name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up and build the backend
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Update to match your Java version

      - name: Build backend
        run: |
          cd backend
          ./mvnw clean install -DskipTests

      # Step 3: Set up and analyze the frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.0' # Update to match your Node.js version

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm run build

      # Step 4: Run SonarCloud analysis
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner
